InterquartileRange.out : InterquartileRange.cpp
	g++ InterquartileRange.cpp -o InterquartileRange.out

StandardDeviation.out : StandardDeviation.cpp
	g++ StandardDeviation.cpp -o StandardDeviation.out

Quartiles.out : Quartiles.cpp
	g++ Quartiles.cpp -o Quartiles.out

all : InterquartileRange.out StandardDeviation.out Quartiles.out

clean:
	rm -r *.out*