ArraysLeftRotation.out : ArraysLeftRotation.cpp
	g++ -std=c++11 ArraysLeftRotation.cpp -o ArraysLeftRotation.out

Staircase.out : Staircase.cpp
	g++ -std=c++11 Staircase.cpp -o Staircase.out
	
DiagonalDifference.out : DiagonalDifference.cpp
	g++ -std=c++11 DiagonalDifference.cpp -o DiagonalDifference.out

all : DiagonalDifference.out Staircase.out

clean:
	rm *.out*