all : InterquartileRange StandardDeviation Quartiles

InterquartileRange : InterquartileRange.cpp
	g++ InterquartileRange.cpp -o InterquartileRange

StandardDeviation : StandardDeviation.cpp
	g++ StandardDeviation.cpp -o StandardDeviation

Quartiles: Quartiles.cpp
	g++ Quartiles.cpp -o Quartiles

clean:
	rm Quartiles StandardDeviation InterquartileRange